<a href="https://colab.research.google.com/github/eilyn0208/MA1042/blob/google-colab/Personal_Finance_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('finaldata.xlsx')

In [3]:
df.shape[0]

120

In [5]:
df["Budget"].min(), df["Budget"].max()

(50, 8000)

In [6]:
df.loc[df["Budget"].idxmin()]

Number                                        9
Date (dd/mm/yy)             2026-05-01 00:00:00
Name of the activity    savings account deposit
Cost                                         50
Budget                                       50
Time invested                                40
Type                                          2
Moment                                        2
No. of people                                 1
Name: 8, dtype: object

In [7]:
df.loc[df["Budget"].idxmax()]

Number                                   20
Date (dd/mm/yy)         2026-08-01 00:00:00
Name of the activity        attending class
Cost                                   5000
Budget                                 8000
Time invested                           240
Type                                      5
Moment                                    1
No. of people                             1
Name: 19, dtype: object

In [8]:
df.groupby("Type")["Cost"].sum()

Type
1     9750
2     2550
3     3530
4    14010
5    37660
6      240
Name: Cost, dtype: int64

In [10]:
df["Date (dd/mm/yy)"].nunique()

26

In [11]:
df["Cost"].sum()

np.int64(67740)

In [12]:
df.loc[df["Type"] == 2, "Cost"].sum()

np.int64(2550)

In [19]:
avg_daily_savings = df.loc[df["Type"] == 2, "Cost"].mean()

In [20]:
wishlist_price = 2000

In [21]:
wishlist_price / avg_daily_savings

np.float64(3.9215686274509802)