<a href="https://colab.research.google.com/github/eilyn0208/MA1042/blob/google-colab/Phase_2_Understanding_the_Data_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd

In [17]:
df = pd.read_excel('data.xlsx')

In [18]:
df.head()

,Number,Date (dd/mm/yy),Name of the activity,Cost,Budget,Time invested,Type,Moment,No. of people
0,1,2026-05-01 00:00:00,Groceries,1300,1500,180,1,2,4
1,2,2026-04-01 00:00:00,Investment in stocks,1600,2000,20,2,1,1
2,3,2026-04-01 00:00:00,dinner at restaurant,260,300,120,1,3,1
3,4,2026-04-01 00:00:00,disney+ subscription,300,300,45,4,3,4
4,5,2026-05-01 00:00:00,yoga class,250,300,50,3,1,1

In [19]:
df.shape

(90, 9)

In [20]:
df.columns

Index(['Number', 'Date (dd/mm/yy)', 'Name of the activity', 'Cost', 'Budget',
       'Time invested', 'Type', 'Moment', 'No. of people'],
      dtype='object')

In [21]:
df.dtypes

Number                   int64
Date (dd/mm/yy)         object
Name of the activity    object
Cost                     int64
Budget                   int64
Time invested            int64
Type                     int64
Moment                   int64
No. of people            int64
dtype: object

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Number                90 non-null     int64
 1   Date (dd/mm/yy)       90 non-null     object
 2   Name of the activity  90 non-null     object
 3   Cost                  90 non-null     int64
 4   Budget                90 non-null     int64
 5   Time invested         90 non-null     int64
 6   Type                  90 non-null     int64
 7   Moment                90 non-null     int64
 8   No. of people         90 non-null     int64
dtypes: int64(7), object(2)
memory usage: 6.5+ KB

In [23]:
df["Cost"].sum()

np.int64(50090)

In [24]:
df["Time invested"].sum()

np.int64(9125)

In [25]:
df["Name of the activity"].value_counts()

Name of the activity
practicing coding           7
studying english            6
doing homework              6
yoga class                  6
ordering food               4
work meeting                3
Groceries                   2
birthday celebration        2
dinner at restaurant        2
attending class             2
Snacks at bf house          2
playing board games         2
hanging out                 2
savings account deposit     1
mall shopping               1
snacks                      1
online shopping             1
doctors appointment         1
lunch at restaurant         1
uber                        1
music subscription          1
medication                  1
haircut                     1
Investment in stocks        1
disney+ subscription        1
fixing something at home    1
breakfast at restaurant     1
cycling                     1
online courses              1
academic research           1
pajamas party               1
bills                       1
pharmacy stuff              1
Dancing                     1
Movies                      1
laundry                     1
Cooking breakfast           1
zumba session               1
charcuterie boxes           1
local market shopping       1
evening walk                1
anniversary date            1
Grocery shopping            1
Playing videogames          1
skincare                    1
cleaning the kitchen        1
playing tennis              1
attending a workshop        1
public transportation       1
attending church            1
journaling                  1
visiting family             1
planing a trip              1
going out                   1
taking photos outside       1
donating                    1
visiting a park             1
Name: count, dtype: int64

In [26]:
df["Moment"].value_counts()

Moment
1    39
2    31
3    20
Name: count, dtype: int64

In [27]:
df["No. of people"].value_counts()

No. of people
1    72
2    10
4     6
5     2
Name: count, dtype: int64

In [28]:
df.loc[df["Cost"].idxmax()]

Number                                   11
Date (dd/mm/yy)         2026-04-01 00:00:00
Name of the activity        online shopping
Cost                                   6700
Budget                                 7000
Time invested                            60
Type                                      4
Moment                                    1
No. of people                             1
Name: 10, dtype: object

In [29]:
df.groupby("Type").sum(numeric_only=True)

      Number   Cost  Budget  Time invested  Moment  No. of people
Type
1        939   7540    8130           1890      52             38
2        148   2550    2950            270       8              5
3        576   2280    2550            820      16             13
4        721  13540   14070           3455      50             37
5       1652  24010   30450           2630      31             31
6         59    170     170             60       4              2

In [30]:
df.describe()

,Number,Cost,Budget,Time invested,Type,Moment,No. of people
count,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000
mean,45.500000,556.555556,648.000000,101.388889,3.344444,1.788889,1.400000
std,26.124701,1088.588573,1428.119845,110.872504,1.629511,0.786036,0.957525
min,1.000000,10.000000,50.000000,10.000000,1.000000,1.000000,1.000000
25%,23.250000,100.000000,100.000000,50.000000,1.250000,1.000000,1.000000
50%,45.500000,225.000000,225.000000,60.000000,4.000000,2.000000,1.000000
75%,67.750000,300.000000,330.000000,120.000000,5.000000,2.000000,1.000000
max,90.000000,6700.000000,8000.000000,780.000000,6.000000,3.000000,5.000000